### ISSUE TITLE
Files not encrypting & server side error

### ISSUE THREAD

**Issue by kiwoon** [mauri870/ransomware#17]
I have a problem..what a happen..?

![error](https://cloud.githubusercontent.com/assets/20625320/23735318/330539f6-04c8-11e7-9e98-d382ad037d65.JPG)

I attached another generate_cert.go source 
succeed  make..
Files not encrypting...  server side error....
help me.........TT

**Comment by mauri870** [comment]
From what I remember 422 is referring to your RSA key. Probably your public and private key does not match. Please try to clean out the project and repeat the README steps

**Comment by mauri870** [comment]
I've fixed these problems with the rsa keys not cleaned after a failed build. If the problem still happens please reopen the issue
