### ISSUE TITLE
help me! make error

### ISSUE THREAD

**Issue by redpeony** [mauri870/ransomware#18]
I do not know programming. But I am studying hard. There was a problem building your project.

![image](https://cloud.githubusercontent.com/assets/26310705/23767754/1a970c48-054d-11e7-8fb6-61244dcd46bf.png)

where is generate_cert.go ? Where can I get it? 
generate_cert.go program it myself? It is harsh for me....TT
I respect you. I need help.

**Comment by redpeony** [comment]
I find generate_cert.go......in this page  https://golang.org/src/crypto/tls/generate_cert.go
success build project. but 
![image](https://cloud.githubusercontent.com/assets/26310705/23768007/ea5827b4-054d-11e7-9e82-b3c19be86499.png)

I see this error. 
please answer me.

**Comment by mauri870** [comment]
Please take a look at #17

**Comment by redpeony** [comment]
Thank you for your reply. this site(https://golang.org/src/crypto/tls/generate_cert.go)... Is the file correct?
If it is correct, we will try again.

**Comment by mauri870** [comment]
Please refer to golang installation docs. Your GOROOT env needs to point to the go source tree

**Comment by redpeony** [comment]
I am really sorry. My status is as follows.

![image](https://cloud.githubusercontent.com/assets/26310705/23770767/b0bcd838-0557-11e7-8e94-2120eff89cc2.png)

is it wrong?

**Comment by mauri870** [comment]
I think it's correct :/

What's your go version?

**Comment by redpeony** [comment]
My version is go1.8 linux / amd64.
Is it a problem to use Kali Linux?

422 Is error also related to file encryption?
When you run the ransomware.exe file, the target file is not encrypted.

**Comment by mauri870** [comment]
422 is possibly related to the RSA keys that not match

Try clean your project and rebuild it again

**Comment by And82** [comment]
Hi, I have the same problem as the friend above. Any solution for this?


![go](https://user-images.githubusercontent.com/29684614/27513708-1cd2bd60-5947-11e7-8bf6-6c08f9b2544e.JPG)

**Comment by And82** [comment]
I did as I said, I deleted the certs and recreated again and the same error appears. Has anyone managed to solve it?

**Comment by mauri870** [comment]
Sorry for the delay guys... I'll push a fix soon

**Comment by And82** [comment]
Many thanks, I'll be waiting for you

**Comment by mauri870** [comment]
@And82 See this [commit](https://github.com/mauri870/ransomware/commit/658ac0b7cb5f028c8d8a9d3454f4e8ecb38d1dda)

I think this will fix the issues related to the rsa keys

**Comment by mauri870** [comment]
Closing this issue, if you have any related problem please open a new one
