### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by max0451** [mauri870/ransomware#19]
I'm just starting out programming and I'm stuck with something here,

it's not encrypting anything, only trying to open the folders and getting access denied. The software runs as administrator.
If I change the code like this though (which you suggested in another issue):
`// Directories to walk searching for files
InterestingDirs = []string{
    UserDir + "Pictures",
    UserDir + "Documents",
    UserDir + "Music",
    UserDir + "Desktop",
    UserDir + "Downloads",
    UserDir + "Videos",
    "E:\\",
}`
It encrypts the files in these folders, but only these folders without subfolders, drive E fails though.

Maybe you can help me out

**Comment by mauri870** [comment]
I think this was fixed by 232a2432a53a05c163769a6dacd9bf63826a467a

**Comment by mauri870** [comment]
Feel free to reopen the issue if you have any questions
