### ISSUE TITLE
Tor support and other features.

### ISSUE THREAD

**Issue by Hanoosh** [mauri870/ransomware#2]
Please have a look at this : https://github.com/lucdew/goransomware

Combining your project with some of that one features like : Tor, Blockchain polling.. is a great idea.
Regards,

**Comment by mauri870** [comment]
Nice ideas! I'll look at that as soon as possible.
I finished all my plans with the malware itself (except the stream encryption) and I will focus on new features.
Have you tested my project?

**Comment by Hanoosh** [comment]
Thanks for your reply, I'll setup a VM for testing and playing with it tomorrow. it is a very good project.

**Comment by mauri870** [comment]
Waiting for your feedback :)
