### ISSUE TITLE
Error with echo while "make".

### ISSUE THREAD

**Issue by john323130** [mauri870/ransomware#27]
I get this error while building:

![275097bce540b264216ae9ae284c9f2f](https://user-images.githubusercontent.com/23268779/31515548-d23f1bd6-af95-11e7-87cc-a1d42a22851f.png)

Help please! :)
@mauri870

**Comment by john323130** [comment]
This happens when I use the v.2.2.0 of echo, I get an error while using the v3 of echo so I guess it isn't supported yet

**Comment by john323130** [comment]
I used v.2.0.0 of echo but now I get this error:

rm -r /root/Desktop/ransomware/bin || true
mkdir -p /root/Desktop/ransomware/build/ransomware /root/Desktop/ransomware/build/unlocker /root/Desktop/ransomware/build/server
openssl genrsa -out /root/Desktop/ransomware/build/server/private.pem 4096
Generating RSA private key, 4096 bit long modulus
............................................................++
...............................++
e is 65537 (0x010001)
openssl rsa -in /root/Desktop/ransomware/build/server/private.pem -outform PEM -pubout -out /root/Desktop/ransomware/build/ransomware/public.pem
writing RSA key
cd /root/Desktop/ransomware/build/ransomware && go-bindata -pkg main -o public_key.go public.pem
rsrc -manifest ransomware.manifest -ico icon.ico -o /root/Desktop/ransomware/build/ransomware/ransomware.syso
cp /root/Desktop/ransomware/build/ransomware/ransomware.syso /root/Desktop/ransomware/build/unlocker/unlocker.syso
cd /root/Desktop/ransomware/cmd && cp -r ransomware unlocker server /root/Desktop/ransomware/build
cd /root/Desktop/ransomware/build/server && env GOOS=linux go run /usr/lib/go//src/crypto/tls/generate_cert.go --host localhost
2017/10/13 10:28:12 written cert.pem
2017/10/13 10:28:12 written key.pem
mkdir -p /root/Desktop/ransomware/bin/server
cd /root/Desktop/ransomware/build/ransomware && GOOS=windows GOARCH=386 go build --ldflags "-s -w -H windowsgui -X main.ServerBaseURL=https://localhost:8080" -o /root/Desktop/ransomware/bin/ransomware.exe
cd /root/Desktop/ransomware/build/unlocker && GOOS=windows GOARCH=386 go build --ldflags "-s -w" -o /root/Desktop/ransomware/bin/unlocker.exe
cd /root/Desktop/ransomware/build/server && go build --ldflags "-s -w -X main.DefaultAddress=localhost:8080" && mv `ls|grep -v 'server.go'` /root/Desktop/ransomware/bin/server
# github.com/labstack/echo
/root/go/src/github.com/labstack/echo/echo.go:234: cannot use l (type *"github.com/labstack/gommon/log".Logger) as type "github.com/labstack/echo/log".Logger in argument to e.SetLogger:
	*"github.com/labstack/gommon/log".Logger does not implement "github.com/labstack/echo/log".Logger (wrong type for SetLevel method)
		have SetLevel("github.com/labstack/gommon/log".Lvl)
		want SetLevel(uint8)
/root/go/src/github.com/labstack/echo/echo.go:315: cannot use "github.com/labstack/gommon/log".DEBUG (type "github.com/labstack/gommon/log".Lvl) as type uint8 in argument to e.SetLogLevel
Makefile:33: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by mauri870** [comment]
The glide.yaml locks the echo dependency at 2.1.x, this version is supposed to work without problems. Please try to stash your changes and repeat the installation instructions. You can also use the docker installation, it is less error prone and don't require a proper environment.
