### ISSUE TITLE
bindata: Input path 'public.pem' is not a directory.

### ISSUE THREAD

**Issue by Metasploiter** [mauri870/ransomware#33]
**First of all, thank you for this great tool
and your support for it 
but I have this problem and I tried to fix this in many ways but it's still happening 
here is my issue:**
==========================================================
cd /home/batman/Go/src/github.com/mauri870/ransomware/build/ransomware && go-bindata -pkg main -o public_key.go public.pem
bindata: Input path 'public.pem' is not a directory.
Makefile:22: recipe for target 'pre-build' failed
make: *** [pre-build] Error 1

**Comment by mauri870** [comment]
The master branch is now updated with a step-by-step demo, can you please try that? If the problem persists feel free to open a new issue :smile:
