### ISSUE TITLE
GOOS=windows make error

### ISSUE THREAD

**Issue by Gembeltz** [mauri870/ransomware#45]
![screenshot from 2018-08-30 17-11-41](https://user-images.githubusercontent.com/33371685/44845460-cae6a900-ac77-11e8-82f3-f35c31d80701.png)

**Comment by Gembeltz** [comment]
![screenshot from 2018-08-30 17-15-38](https://user-images.githubusercontent.com/33371685/44845759-94f5f480-ac78-11e8-9698-3d1ff7b0989f.png)
how to fix

**Comment by awesomeness111** [comment]
Same :
make -e GOOS=windows
rm -r /root/ransomware/bin || true
rm: cannot remove '/root/ransomware/bin': No such file or directory
mkdir -p /root/ransomware/build/ransomware /root/ransomware/build/unlocker /root/ransomware/build/server
openssl genrsa -out /root/ransomware/build/server/private.pem 4096
Generating RSA private key, 4096 bit long modulus
...................................................++
..............................................................................................................................................++
e is 65537 (0x010001)
openssl rsa -in /root/ransomware/build/server/private.pem -outform PEM -pubout -out /root/ransomware/build/ransomware/public.pem
writing RSA key
cd /root/ransomware/build/ransomware && go-bindata -pkg main -o public_key.go public.pem
rsrc -manifest ransomware.manifest -ico icon.ico -o /root/ransomware/build/ransomware/ransomware.syso
cp /root/ransomware/build/ransomware/ransomware.syso /root/ransomware/build/unlocker/unlocker.syso
cd /root/ransomware/cmd && cp -r ransomware unlocker server /root/ransomware/build
cd /root/ransomware/build/server && env GOOS=linux go run /src/crypto/tls/generate_cert.go --host localhost
stat /src/crypto/tls/generate_cert.go: no such file or directory
Makefile:21: recipe for target 'pre-build' failed
make: *** [pre-build] Error 1

**Comment by awesomeness111** [comment]
Found solution. All is ok. Thanks.

**Comment by mbda81** [comment]
how did you solve it?

**Comment by mauri870** [comment]
Set $GOROOT to point to your Go source tree. In my case is /usr/local/go
