### ISSUE TITLE
Add drive 

### ISSUE THREAD

**Issue by appendhc** [mauri870/ransomware#6]
Hi 
This ransomware only lock userprofile folder 
Please add a option for support all drive 
C: d: and other 
But in c: don't lock any thing in program files and eindows folder

**Comment by mauri870** [comment]
Hi @appendhc 

I will add more flexibility for folders, thanks

Generally crypto-ransomwares encrypt only personal files for prevent system crashes. Probably encrypt Program Files or the Windows folder will cause instability and the process cannot be finished properly.
